name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2.4.0
        with:
          node-version: '16'
          cache: 'yarn'

      - name: install
        run: |
          yarn install --frozen-lockfile

      - name: Setup next.js build cache
        uses: actions/cache@v2.1.6
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: build
        run: |
          yarn build
        env:
          GITHUB_PAGES: true

      - name: export
        run: |
          yarn export
          touch out/.nojekyll

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: watta.org
